version: "3"
services:
  node:
    image: "backend"
    build: 
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    restart: always
    ports:
     - 3000:3000
    volumes:
      # - /app/node_modules
      - .:/app